model: model.st_gcn.Model

model_args:
  in_channels: 3
  num_person: 2
  num_class: 3
  graph: graph.h36m.Graph


  graph_args:
    labeling_mode: spatial


loss : torch.nn.CrossEntropyLoss
loss_args : {}

num_epoch : 40
patience : 7

evaluation_method : leave_pair_out
train_data_path : ./data/MB_3DP/1/data.npy
train_label_path : ./data/MB_3DP/1/label.npy
test_data_path : ./data/MB_3DP/1/data.npy
test_label_path : ./data/MB_3DP/1/label.npy
leave_pair : [1,2,3,4]
train_walkpath : [1]
test_walkpath : [1]
batch_size : 32
data_augment:
  joint_courruption : False
